### PR TITLE
test discovery

### PR DESCRIPTION
**Pull request by Garcia6l20**
- adding doctest discovery (doctest.cmake)

### CODE REVIEW

**Comment by andreasbuhr** [comment]
Wow, this is really great! I merged "integrate_all" and your proposed change and pushed it as branch "deleteme2" to see what github actions do. In all configurations, the test "multi-threaded" runs into a timeout, see https://github.com/andreasbuhr/cppcoro/runs/1248616370 . Did you also observe this? Is this easy to fix? If not, can we disable the test until we have a fix?

**Comment by Garcia6l20** [comment]
I've been lucky: https://github.com/Garcia6l20/cppcoro/runs/1252808292?check_suite_focus=true
But this test took 23.7 sec, so maybe we should set an higher timeout !

**Comment by Garcia6l20** [comment]
Do you observe this behavior on you laptop ?
I dont, so I think it might be related to BH's VMs, don't you think so ?

**Comment by Garcia6l20** [comment]
Notice we have 2 multi-threaded test,
TEST_SUITE are not (yet) handled by doctest_discover_tests

https://github.com/onqtam/doctest/issues/302

**Comment by andreasbuhr** [comment]
Increasing the timeout for the one test which sometimes runs into timeout sound like a good solution to me. Would you do it?

**Comment by Garcia6l20** [comment]
Yes,
I also added sanitizers in my io_service branch, it would be really helpful for everyone, but we will also have to update doctest cause the version we are using have some problems with that, and it looks like it have been resolved on current master branch.

**Comment by andreasbuhr** [comment]
Hi, oh yes, sanitizers would be cool. 
Just that I understand it correctly: An update to doctest version 2.4.0 as I prepared in https://github.com/lewissbaker/cppcoro/pull/178 would not be sufficient? Does it have to be current master branch?

**Comment by Garcia6l20** [comment]
Idk, I just know they are fixed now I'll try out this version after.

**Comment by Garcia6l20** [comment]
Looks ok : https://github.com/Garcia6l20/cppcoro/runs/1255305707

**Comment by Garcia6l20** [comment]
Well it work... hum... it fails but it works :)
I forced a leak cause we cppcoro looks leak-free :)

https://github.com/Garcia6l20/cppcoro/runs/1255719412

ubsan seems not working with coroutines
and we'll have to investigate with tsan

**Comment by andreasbuhr** [comment]
This looks really great, thank you so much.

**Pull request merged**
