### PR TITLE
add C++17 test configurations

### PR DESCRIPTION
**Pull request by andreasbuhr**

### CODE REVIEW

**Comment by andreasbuhr** [comment]
This should work fine as soon as https://github.com/andreasbuhr/cppcoro/pull/23 and https://github.com/andreasbuhr/cppcoro/pull/24 are merged.

**Comment by tobias-loew** [comment]
I can confirm @andreasbuhr's obeservation: merging this PR with #23 and #24 repairs the failing tests!

**Comment by andreasbuhr** [comment]
It seems we were mistaken: I merged https://github.com/andreasbuhr/cppcoro/pull/23 and https://github.com/andreasbuhr/cppcoro/pull/24 and rebased this PR on top of them. With MSVC 2019 and C++17, it fails. @tobias-loew if you could have a look into this, that would be great.

**Comment by andreasbuhr** [comment]
@tobias-loew what would you think about this?

**Comment by tobias-loew** [comment]
The issue send fixed: FindCoroutines.cnake is evaluated as expected for all configurations!

**Pull request merged**
